#include <stdio.h>
#include <windows.h>

enum color
{
	black		= 0,
	darkgrey	= FOREGROUND_INTENSITY,
	darkgray	= FOREGROUND_INTENSITY,
	grey		= FOREGROUND_RED   | FOREGROUND_GREEN | FOREGROUND_BLUE,
	gray		= FOREGROUND_RED   | FOREGROUND_GREEN | FOREGROUND_BLUE,
	white		= FOREGROUND_RED   | FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY,
	darkblue	= FOREGROUND_BLUE,
	darkgreen	= FOREGROUND_GREEN,
	darkcyan	= FOREGROUND_GREEN | FOREGROUND_BLUE,
	darkred		= FOREGROUND_RED,
	darkpurple	= FOREGROUND_RED   | FOREGROUND_BLUE,
	darkyellow	= FOREGROUND_RED   | FOREGROUND_GREEN,
	blue		= FOREGROUND_BLUE  | FOREGROUND_INTENSITY,
	green		= FOREGROUND_GREEN | FOREGROUND_INTENSITY,
	cyan		= FOREGROUND_GREEN | FOREGROUND_BLUE  | FOREGROUND_INTENSITY,
	red			= FOREGROUND_RED   | FOREGROUND_INTENSITY,
	purple		= FOREGROUND_RED   | FOREGROUND_BLUE  | FOREGROUND_INTENSITY,
	yellow		= FOREGROUND_RED   | FOREGROUND_GREEN | FOREGROUND_INTENSITY,
};

void SetColor(color fgColor)
{
	HANDLE hConsole;
	hConsole = GetStdHandle(STD_OUTPUT_HANDLE);
	if (hConsole != INVALID_HANDLE_VALUE)
		SetConsoleTextAttribute(hConsole, fgColor);
}
